//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public int id { get; set; }
        public string cname { get; set; }
        public string ctype { get; set; }
        public Nullable<int> flag_id { get; set; }
        public string createdby { get; set; }
        public string modiffiedby { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.DateTime modifiedDate { get; set; }
        public string meta_keys { get; set; }
        public string meta_description { get; set; }
    
        public virtual flag flag { get; set; }
    }
}
