//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class feed_contact_review
    {
        public int id { get; set; }
        public Nullable<int> customers_id { get; set; }
        public string Name { get; set; }
        public Nullable<byte> good { get; set; }
        public Nullable<byte> slow { get; set; }
        public Nullable<byte> fast { get; set; }
        public Nullable<int> items_id { get; set; }
        public int albumId { get; set; }
        public Nullable<int> parentId { get; set; }
        public Nullable<int> rating { get; set; }
        public byte[] emoji_img { get; set; }
        public string Email { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual flag flag { get; set; }
        public virtual register register { get; set; }
    }
}
