//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class genre
    {
        public int id { get; set; }
        public string genresName { get; set; }
        public string createdby { get; set; }
        public string genreImg { get; set; }
        public string nodifiedby { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    }
}
