//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int id { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string cpass { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> roles_Id { get; set; }
    
        public virtual role role { get; set; }
        public virtual register register { get; set; }
    }
}
