//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineNews
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnlineNewsEntities : DbContext
    {
        public OnlineNewsEntities()
            : base("name=OnlineNewsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<feed_contact_review> feed_contact_review { get; set; }
        public virtual DbSet<flag> flags { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<register> registers { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<category> categories { get; set; }
    
        public virtual int media(Nullable<int> doctypeid)
        {
            var doctypeidParameter = doctypeid.HasValue ?
                new ObjectParameter("doctypeid", doctypeid) :
                new ObjectParameter("doctypeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("media", doctypeidParameter);
        }
    
        public virtual int ms_media(Nullable<int> doctypeid)
        {
            var doctypeidParameter = doctypeid.HasValue ?
                new ObjectParameter("doctypeid", doctypeid) :
                new ObjectParameter("doctypeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ms_media", doctypeidParameter);
        }
    }
}
