//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int id { get; set; }
        public string newsTitle { get; set; }
        public string newsDescription { get; set; }
        public Nullable<int> category_id { get; set; }
        public string news_img { get; set; }
        public Nullable<byte> active { get; set; }
        public string createdby { get; set; }
        public string modifiedby { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.DateTime modifiedDate { get; set; }
    }
}
