//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class register
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public register()
        {
            this.feed_contact_review = new HashSet<feed_contact_review>();
            this.logins = new HashSet<login>();
        }
    
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string country { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string gender { get; set; }
        public string dob { get; set; }
        public string CompanyName { get; set; }
        public string companyTitle { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string PostalCode { get; set; }
        public string Fax { get; set; }
        public string url { get; set; }
        public string img { get; set; }
        public string Payment_id { get; set; }
        public Nullable<int> accountTypeId { get; set; }
        public string cardholderName { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> CVV { get; set; }
        public string cardNumber { get; set; }
        public Nullable<int> userTypeId { get; set; }
        public Nullable<int> parentId { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.DateTime modifiedDate { get; set; }
        public Nullable<int> flag_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feed_contact_review> feed_contact_review { get; set; }
        public virtual flag flag { get; set; }
        public virtual flag flag1 { get; set; }
        public virtual flag flag2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<login> logins { get; set; }
    }
}
